<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xVe5a3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xVe5a3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xVe5a3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xVe5a3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xVe5a3\App_KernelDevDebugContainer([
    'container.build_hash' => '0xVe5a3',
    'container.build_id' => '033cdd0d',
    'container.build_time' => 1687268851,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xVe5a3');
